<?php

namespace ContainerZjFNx9t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEstadisticasEnlacesControllerobtenerEstadisticasPorFechaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Svls8H_.App\Controller\EstadisticasEnlacesController::obtenerEstadisticasPorFecha()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Svls8H_.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'servicio_fechas' => ['privates', 'App\\Services\\FechasService', 'getFechasServiceService', true],
        ], [
            'entityManager' => '?',
            'servicio_fechas' => 'App\\Services\\FechasService',
        ]))->withContext('App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha()', $container);
    }
}
