<?php

namespace ContainerZjFNx9t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFechasServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\FechasService' shared autowired service.
     *
     * @return \App\Services\FechasService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FechasService.php';

        return $container->privates['App\\Services\\FechasService'] = new \App\Services\FechasService();
    }
}
