<?php

namespace ContainerXL1pg25;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiltrarUrlServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\FiltrarUrlService' shared autowired service.
     *
     * @return \App\Services\FiltrarUrlService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FiltrarUrlService.php';

        return $container->privates['App\\Services\\FiltrarUrlService'] = new \App\Services\FiltrarUrlService(($container->privates['App\\Repository\\EnlacesRepository'] ?? $container->load('getEnlacesRepositoryService')));
    }
}
