<?php

namespace ContainerPC0Kzob;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistroControllerregistroService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jWo6Ji9.App\Controller\RegistroController::registro()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jWo6Ji9.App\\Controller\\RegistroController::registro()'] = ($container->privates['.service_locator.jWo6Ji9'] ?? $container->load('get_ServiceLocator_JWo6Ji9Service'))->withContext('App\\Controller\\RegistroController::registro()', $container);
    }
}
