<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjFNx9t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjFNx9t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZjFNx9t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZjFNx9t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZjFNx9t\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZjFNx9t',
    'container.build_id' => '41ac6d05',
    'container.build_time' => 1745891716,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjFNx9t');
