<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEHxToxP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEHxToxP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEHxToxP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEHxToxP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEHxToxP\App_KernelDevDebugContainer([
    'container.build_hash' => 'EHxToxP',
    'container.build_id' => 'ba310671',
    'container.build_time' => 1744139025,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEHxToxP');
