<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'acortar_url' => [[], ['_controller' => 'App\\Controller\\EnlacesController::acortarUrl'], [], [['text', '/acortarUrl']], [], [], []],
    'app_enlaces' => [[], ['_controller' => 'App\\Controller\\EnlacesController::personalizarUrl'], [], [['text', '/personalizarUrl']], [], [], []],
    'get_user_enlaces' => [[], ['_controller' => 'App\\Controller\\EnlacesController::getUserEnlaces'], [], [['text', '/enlaces-usuario']], [], [], []],
    'eliminar_enlace' => [['id'], ['_controller' => 'App\\Controller\\EnlacesController::eliminarEnlace'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/eliminar-enlace']], [], [], []],
    'obtener_estadisticas' => [['id'], ['_controller' => 'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas'], [], [['text', '/estadisticas'], ['variable', '/', '[^/]++', 'id', true], ['text', '/enlace']], [], [], []],
    'app_redireccionapp_redireccion' => [['urlCorta'], ['_controller' => 'App\\Controller\\RedireccionController::redirectToOriginalUrl'], [], [['variable', '/', '[^/]++', 'urlCorta', true], ['text', '/wbt.es']], [], [], []],
    'app_registro' => [[], ['_controller' => 'App\\Controller\\RegistroController::registro'], [], [['text', '/registro']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\RegistroController::login'], [], [['text', '/login']], [], [], []],
    'app_session' => [[], ['_controller' => 'App\\Controller\\RegistroController::getSessionData'], [], [['text', '/session']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'App\Controller\EnlacesController::acortarUrl' => [[], ['_controller' => 'App\\Controller\\EnlacesController::acortarUrl'], [], [['text', '/acortarUrl']], [], [], []],
    'App\Controller\EnlacesController::personalizarUrl' => [[], ['_controller' => 'App\\Controller\\EnlacesController::personalizarUrl'], [], [['text', '/personalizarUrl']], [], [], []],
    'App\Controller\EnlacesController::getUserEnlaces' => [[], ['_controller' => 'App\\Controller\\EnlacesController::getUserEnlaces'], [], [['text', '/enlaces-usuario']], [], [], []],
    'App\Controller\EnlacesController::eliminarEnlace' => [['id'], ['_controller' => 'App\\Controller\\EnlacesController::eliminarEnlace'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/eliminar-enlace']], [], [], []],
    'App\Controller\EstadisticasEnlacesController::obtenerEstadisticas' => [['id'], ['_controller' => 'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas'], [], [['text', '/estadisticas'], ['variable', '/', '[^/]++', 'id', true], ['text', '/enlace']], [], [], []],
    'App\Controller\RedireccionController::redirectToOriginalUrl' => [['urlCorta'], ['_controller' => 'App\\Controller\\RedireccionController::redirectToOriginalUrl'], [], [['variable', '/', '[^/]++', 'urlCorta', true], ['text', '/wbt.es']], [], [], []],
    'App\Controller\RegistroController::registro' => [[], ['_controller' => 'App\\Controller\\RegistroController::registro'], [], [['text', '/registro']], [], [], []],
    'App\Controller\RegistroController::login' => [[], ['_controller' => 'App\\Controller\\RegistroController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\RegistroController::getSessionData' => [[], ['_controller' => 'App\\Controller\\RegistroController::getSessionData'], [], [['text', '/session']], [], [], []],
];
