<?php

namespace ContainerWNjSLT8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PYAwkHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PYAwk_h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PYAwk_h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EnlacesController::acortarUrl' => ['privates', '.service_locator.l9AAz2_.App\\Controller\\EnlacesController::acortarUrl()', 'getEnlacesControlleracortarUrlService', true],
            'App\\Controller\\EnlacesController::personalizarUrl' => ['privates', '.service_locator.M5PgiJv.App\\Controller\\EnlacesController::personalizarUrl()', 'getEnlacesControllerpersonalizarUrlService', true],
            'App\\Controller\\EnlacesController::getUserEnlaces' => ['privates', '.service_locator.iXC9NKv.App\\Controller\\EnlacesController::getUserEnlaces()', 'getEnlacesControllergetUserEnlacesService', true],
            'App\\Controller\\EnlacesController::eliminarEnlace' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EnlacesController::eliminarEnlace()', 'getEnlacesControllereliminarEnlaceService', true],
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas()', 'getEstadisticasEnlacesControllerobtenerEstadisticasService', true],
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorPais' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorPais()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorPaisService', true],
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorFechaService', true],
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorDispositivo' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorDispositivo()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorDispositivoService', true],
            'App\\Controller\\RedireccionController::redirectToOriginalUrl' => ['privates', '.service_locator.TMleYZy.App\\Controller\\RedireccionController::redirectToOriginalUrl()', 'getRedireccionControllerredirectToOriginalUrlService', true],
            'App\\Controller\\RegistroController::registro' => ['privates', '.service_locator.jWo6Ji9.App\\Controller\\RegistroController::registro()', 'getRegistroControllerregistroService', true],
            'App\\Controller\\RegistroController::login' => ['privates', '.service_locator.K6BUKFy.App\\Controller\\RegistroController::login()', 'getRegistroControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EnlacesController:acortarUrl' => ['privates', '.service_locator.l9AAz2_.App\\Controller\\EnlacesController::acortarUrl()', 'getEnlacesControlleracortarUrlService', true],
            'App\\Controller\\EnlacesController:personalizarUrl' => ['privates', '.service_locator.M5PgiJv.App\\Controller\\EnlacesController::personalizarUrl()', 'getEnlacesControllerpersonalizarUrlService', true],
            'App\\Controller\\EnlacesController:getUserEnlaces' => ['privates', '.service_locator.iXC9NKv.App\\Controller\\EnlacesController::getUserEnlaces()', 'getEnlacesControllergetUserEnlacesService', true],
            'App\\Controller\\EnlacesController:eliminarEnlace' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EnlacesController::eliminarEnlace()', 'getEnlacesControllereliminarEnlaceService', true],
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticas' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas()', 'getEstadisticasEnlacesControllerobtenerEstadisticasService', true],
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorPais' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorPais()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorPaisService', true],
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorFecha' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorFechaService', true],
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorDispositivo' => ['privates', '.service_locator.P.blNFL.App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorDispositivo()', 'getEstadisticasEnlacesControllerobtenerEstadisticasPorDispositivoService', true],
            'App\\Controller\\RedireccionController:redirectToOriginalUrl' => ['privates', '.service_locator.TMleYZy.App\\Controller\\RedireccionController::redirectToOriginalUrl()', 'getRedireccionControllerredirectToOriginalUrlService', true],
            'App\\Controller\\RegistroController:registro' => ['privates', '.service_locator.jWo6Ji9.App\\Controller\\RegistroController::registro()', 'getRegistroControllerregistroService', true],
            'App\\Controller\\RegistroController:login' => ['privates', '.service_locator.K6BUKFy.App\\Controller\\RegistroController::login()', 'getRegistroControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EnlacesController::acortarUrl' => '?',
            'App\\Controller\\EnlacesController::personalizarUrl' => '?',
            'App\\Controller\\EnlacesController::getUserEnlaces' => '?',
            'App\\Controller\\EnlacesController::eliminarEnlace' => '?',
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticas' => '?',
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorPais' => '?',
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorFecha' => '?',
            'App\\Controller\\EstadisticasEnlacesController::obtenerEstadisticasPorDispositivo' => '?',
            'App\\Controller\\RedireccionController::redirectToOriginalUrl' => '?',
            'App\\Controller\\RegistroController::registro' => '?',
            'App\\Controller\\RegistroController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EnlacesController:acortarUrl' => '?',
            'App\\Controller\\EnlacesController:personalizarUrl' => '?',
            'App\\Controller\\EnlacesController:getUserEnlaces' => '?',
            'App\\Controller\\EnlacesController:eliminarEnlace' => '?',
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticas' => '?',
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorPais' => '?',
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorFecha' => '?',
            'App\\Controller\\EstadisticasEnlacesController:obtenerEstadisticasPorDispositivo' => '?',
            'App\\Controller\\RedireccionController:redirectToOriginalUrl' => '?',
            'App\\Controller\\RegistroController:registro' => '?',
            'App\\Controller\\RegistroController:login' => '?',
        ]);
    }
}
