<?php

namespace ContainerWNjSLT8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedireccionControllerredirectToOriginalUrlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TMleYZy.App\Controller\RedireccionController::redirectToOriginalUrl()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TMleYZy.App\\Controller\\RedireccionController::redirectToOriginalUrl()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enlaceRepository' => ['privates', 'App\\Repository\\EnlacesRepository', 'getEnlacesRepositoryService', true],
        ], [
            'enlaceRepository' => 'App\\Repository\\EnlacesRepository',
        ]))->withContext('App\\Controller\\RedireccionController::redirectToOriginalUrl()', $container);
    }
}
