<?php

namespace ContainerEHxToxP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnlacesControllerpersonalizarUrlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M5PgiJv.App\Controller\EnlacesController::personalizarUrl()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M5PgiJv.App\\Controller\\EnlacesController::personalizarUrl()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enlacesRepository' => ['privates', 'App\\Repository\\EnlacesRepository', 'getEnlacesRepositoryService', true],
            'filtroUrl' => ['privates', 'App\\Services\\FiltrarUrlService', 'getFiltrarUrlServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'enlacesRepository' => 'App\\Repository\\EnlacesRepository',
            'filtroUrl' => 'App\\Services\\FiltrarUrlService',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\EnlacesController::personalizarUrl()', $container);
    }
}
