<?php

namespace Container5OTHGll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnlacesControllergetUserEnlacesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iXC9NKv.App\Controller\EnlacesController::getUserEnlaces()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iXC9NKv.App\\Controller\\EnlacesController::getUserEnlaces()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enlacesRepository' => ['privates', 'App\\Repository\\EnlacesRepository', 'getEnlacesRepositoryService', true],
        ], [
            'enlacesRepository' => 'App\\Repository\\EnlacesRepository',
        ]))->withContext('App\\Controller\\EnlacesController::getUserEnlaces()', $container);
    }
}
