<?php

namespace Container5OTHGll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnlacesControlleracortarUrlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l9AAz2_.App\Controller\EnlacesController::acortarUrl()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l9AAz2_.App\\Controller\\EnlacesController::acortarUrl()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acortador' => ['privates', 'App\\Services\\AcortarUrlService', 'getAcortarUrlServiceService', true],
            'enlacesRepository' => ['privates', 'App\\Repository\\EnlacesRepository', 'getEnlacesRepositoryService', true],
            'filtroUrl' => ['privates', 'App\\Services\\FiltrarUrlService', 'getFiltrarUrlServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'acortador' => 'App\\Services\\AcortarUrlService',
            'enlacesRepository' => 'App\\Repository\\EnlacesRepository',
            'filtroUrl' => 'App\\Services\\FiltrarUrlService',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\EnlacesController::acortarUrl()', $container);
    }
}
